kong:
  # DB-less mode
  env:
    database: "off"

  # Prepare for k8s Ingress manifests
  ingressController:
    enabled: true
    ingressClass: kong

  # There's an HTTP2 bug in Kong which creates
  # an excess of noise in the proxy logs.
  # The fix will be in Kong 2.8.2
  # https://github.com/Kong/kong/pull/8690
  admin:
    tls:
      parameters: []